# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1016, 755)
        MainWindow.setMinimumSize(QtCore.QSize(1016, 755))
        MainWindow.setMaximumSize(QtCore.QSize(1016, 755))
        MainWindow.setStyleSheet("QWidget#centralwidget {\n"
"    background-image: url(C:/git/budgetAuto/budgetAutomation/resources/budget_back.jpg);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(290, 150, 381, 471))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.login_line = QtWidgets.QLineEdit(self.groupBox)
        self.login_line.setGeometry(QtCore.QRect(50, 70, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.login_line.setFont(font)
        self.login_line.setAlignment(QtCore.Qt.AlignCenter)
        self.login_line.setObjectName("login_line")
        self.password_line = QtWidgets.QLineEdit(self.groupBox)
        self.password_line.setGeometry(QtCore.QRect(50, 200, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.password_line.setFont(font)
        self.password_line.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_line.setAlignment(QtCore.Qt.AlignCenter)
        self.password_line.setObjectName("password_line")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(90, 40, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(205, 205, 205);\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(90, 170, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(205, 205, 205);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.enter_button = QtWidgets.QPushButton(self.groupBox)
        self.enter_button.setGeometry(QtCore.QRect(20, 290, 341, 121))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.enter_button.setFont(font)
        self.enter_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.enter_button.setStyleSheet("color: rgb(10,110, 210);\n"
"background-color: rgb(230, 230, 230);\n"
"selection-background-color: rgb(204, 204, 204);")
        self.enter_button.setObjectName("enter_button")
        self.register_button = QtWidgets.QLabel(self.groupBox)
        self.register_button.setGeometry(QtCore.QRect(50, 430, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.register_button.setFont(font)
        self.register_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.register_button.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.register_button.setStyleSheet("color: rgb(10, 120, 210);\n"
"background-color:  rgb(230, 230, 230);\n"
"selection-background-color: rgb(204, 204, 204);")
        self.register_button.setAlignment(QtCore.Qt.AlignCenter)
        self.register_button.setObjectName("register_button")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(240, 10, 481, 181))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1016, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "ЛОГИН"))
        self.label_3.setText(_translate("MainWindow", "ПАРОЛЬ"))
        self.enter_button.setText(_translate("MainWindow", "ВОЙТИ"))
        self.register_button.setText(_translate("MainWindow", "У меня нет аккаунта"))
        self.label_4.setText(_translate("MainWindow", "АВТОМАТИЗАЦИЯ ДОМАШНЕГО БЮДЖЕТА"))
